# Generated by Django 4.1.1 on 2022-10-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layanan',
            name='hargalayanan',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pelayan',
            name='idpelayan',
            field=models.AutoField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pelayan',
            name='notelp',
            field=models.IntegerField(),
        ),
    ]
