# Generated by Django 4.1.1 on 2022-10-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_layanan_hargalayanan_alter_pelayan_idpelayan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaillayanan',
            name='iddetaillayanan',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='layanan',
            name='idlayanan',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pelayan',
            name='idpelayan',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='idtransaksi',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
